### Site Settings ###
title               : Jar of Eyes
description         : 
  <p>Hi, my name is Lyla (she/her)! I'm a Massachusetts-based TTRPG writer and project manager. I have a <a href="https://www.jarofeyes.com/about/">background</a> in teaching and technology and am a <a href="https://www.storytellingcollective.com/pages/creative-laureates">2023 Storytelling Collective Creative Laureate</a>.</p><p>See <a href="https://www.jarofeyes.com/projects/">Projects</a> for a portfolio of my work. For game updates, design advice, and freebies read my newsletter and blog, <a href="https://jarofeyes.substack.com">The Jar of Eyes Game Gazette</a>.</p><p>Want to make games together or chat about your projects? Send me an email at jarofeyesgames(at)gmail.com!</p>
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
#repository          : YoussefRaafatNasry/portfolYOU     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : true                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/blog.html
  - pages/about.md
  # - pages/projects.html
  # - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Lyla
  image             : /images/logo.png
# behance           : your_username
# dribbble          : your_username
  email             : jarofeyesgames@gmail.com
# facebook          : your_username
  github            : ceruleanotter
# gitlab            : your_username
  instagram         : ceruleanotter
# kaggle            : your_username
  linkedin          : lylafujiwara
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
  stackoverflow     : 497605
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : ceruleanotter
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  # elements:                                             # For Documentation Only
  #   output: true                                        # For Documentation Only


### Disqus ###
# disqus:
#   shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  # - scope:                                              # For Documentation Only
  #     path: ""                                          # For Documentation Only
  #     type: "elements"                                  # For Documentation Only
  #   values:                                             # For Documentation Only
  #     layout: "element"                                 # For Documentation Only
  # - scope:
  #     path: ""
  #     type: "posts"
  #   values:
  #     comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
